name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build ghcr.io/day8/demo
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: day8/demo
          tag_semver: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: demo
          no_push: true