name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/core
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: day8/dockerfile-for-dev-ci-image/core
          tag_semver: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: core
          no_push: true
      - name: Build docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/chrome-latest
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: day8/dockerfile-for-dev-ci-image/chrome-latest
          tag_semver: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: chrome-latest
          no_push: true
      - name: Build docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/chrome-56
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: day8/dockerfile-for-dev-ci-image/chrome-56
          tag_semver: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: chrome-56
          no_push: true