name: cd
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build ghcr.io/day8/demo
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          # day8/dockerfile-for-dev-ci-image/demo
          name: day8/demo
          tag_semver: true
          # registry: docker.pkg.github.com
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: demo