name: cd
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/core
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: core
          tag_semver: true
          registry: docker.pkg.github.com/day8/dockerfile-for-dev-ci-image
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: core
      - name: Build docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/chrome-56
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: chrome-56
          tag_semver: true
          registry: docker.pkg.github.com/day8/dockerfile-for-dev-ci-image
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: chrome-56
      - name: Build docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/chrome-latest
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: chrome-latest
          tag_semver: true
          registry: docker.pkg.github.com/day8/dockerfile-for-dev-ci-image
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: chrome-latest
      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: always()
        with:
          type: ${{ job.status  }}
          job_name: dev-ci Docker Image Release
          channel: '#lib-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}