name: cd
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build ghcr.io/day8/core
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: day8/core
          tag_names: true
          tags: "latest"
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: core
      - name: Build ghcr.io/day8/chrome-latest
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: day8/chrome-latest
          tag_names: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: chrome-latest
      - name: Build ghcr.io/day8/chrome-56
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: day8/chrome-56
          tag_names: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
          workdir: chrome-56
      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: always()
        with:
          type: ${{ job.status  }}
          job_name: dev-ci Docker Image Release
          channel: '#lib-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GLOBAL_TOKEN_FOR_GITHUB }}
